// Auto-generated from animals.txt — do not edit by hand.
// Each part list holds animals that contribute that body part.
// TYPES maps every animal to one of the categories in TYPE_ORDER.

export const PART_ORDER = ["base","head","ears","eyes","nose","legs","feet","tail","coat","colour","extra"];

export const PART_LABELS = {
  base: "Base", head: "Head", ears: "Ears", eyes: "Eyes", nose: "Nose",
  legs: "Legs", feet: "Feet", tail: "Tail", coat: "Coat", colour: "Colour", extra: "Extra"
};

export const TYPE_ORDER = ["mammal","bird","fish","reptile","amphibian","insect","bug","sea","dino","mythical"];

export const TYPE_META = {
  mammal:    { label: "Mammals",     emoji: "🦊" },
  bird:      { label: "Birds",       emoji: "🐦" },
  fish:      { label: "Fish",        emoji: "🐠" },
  reptile:   { label: "Reptiles",    emoji: "🦎" },
  amphibian: { label: "Amphibians",  emoji: "🐸" },
  insect:    { label: "Insects",     emoji: "🐝" },
  bug:       { label: "Bugs",        emoji: "🕷️" },
  sea:       { label: "Sea life",    emoji: "🦑" },
  dino:      { label: "Dinosaurs",   emoji: "🦕" },
  mythical:  { label: "Mythical",    emoji: "🦄" }
};

export const PARTS = {
  "base": [
    "harvest mouse",
    "duck",
    "horse",
    "moose",
    "sheep",
    "crocodile",
    "bat",
    "seal",
    "monkey",
    "meerkat",
    "brown bear",
    "sloth bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "flamingo",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "afghan hound",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bedlington terrier",
    "bison",
    "bobcat",
    "budgerigar",
    "capybara",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "giant tortoise",
    "river dolphin",
    "clawed frog",
    "angelfish",
    "ant",
    "giant hornet",
    "barracuda",
    "basenji",
    "basking shark",
    "basset hound",
    "bearded dragon",
    "beaver",
    "bichon frise",
    "birman",
    "black russian terrier",
    "bloodhound",
    "blue jay",
    "blue whale",
    "bombay",
    "booby",
    "border collie",
    "boxer",
    "bumblebee",
    "bullfrog",
    "bull shark",
    "bull terrier",
    "great white shark",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "dogue de bordeaux",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "dama gazelle",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "mimic poison frog",
    "amazon milk frog",
    "dyeing dart frog",
    "phantasmal poison frog",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "doberman",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "british timber",
    "pink fairy armadillo",
    "eurasian jay",
    "mandarin rat snake",
    "blue gourami",
    "rainbow wrasse",
    "scarlet tanager",
    "green iguana",
    "mandarin vole",
    "blue-tailed skink",
    "scarlet ibis",
    "glossy ibis",
    "mandarin catfish",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "bare-throated bellbird",
    "king bird-of-paradise",
    "wilson's bird-of-paradise",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "chihuahua",
    "whippet",
    "shih tzu",
    "puli",
    "eastern bluebird",
    "peregrine falcon",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "goldcrest",
    "common yellowthroat",
    "welcome swallow",
    "white-throated swift",
    "black vulture",
    "violet-green swallow",
    "house finch",
    "yellow-bellied sapsucker",
    "common moorhen",
    "great crested grebe",
    "chimney swift",
    "silvereye",
    "eurasian golden oriole",
    "pink-eared duck",
    "black-chinned hummingbird",
    "lazuli bunting",
    "anna's hummingbird",
    "green heron",
    "yellow-breasted chat",
    "chestnut-collared longspur",
    "yellow-billed cuckoo",
    "tui",
    "superb lyrebird",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "japanese serow",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki"
  ],
  "head": [
    "harvest mouse",
    "duck",
    "horse",
    "moose",
    "sheep",
    "crocodile",
    "bat",
    "seal",
    "monkey",
    "meerkat",
    "brown bear",
    "sloth bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "flamingo",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "afghan hound",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bedlington terrier",
    "bison",
    "bobcat",
    "budgerigar",
    "capybara",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "affenpinscher",
    "ainu dog",
    "airedale terrier",
    "giant tortoise",
    "river dolphin",
    "american bulldog",
    "clawed frog",
    "angelfish",
    "ant",
    "appenzeller dog",
    "giant hornet",
    "cattle dog",
    "australian shepherd",
    "barracuda",
    "basenji",
    "basking shark",
    "basset hound",
    "bearded dragon",
    "beaver",
    "bichon frise",
    "birman",
    "black russian terrier",
    "bloodhound",
    "blue jay",
    "blue whale",
    "bluetick coonhound",
    "bombay",
    "booby",
    "border collie",
    "border terrier",
    "boston terrier",
    "boxer",
    "bumblebee",
    "bullfrog",
    "bull shark",
    "bull terrier",
    "great white shark",
    "cairn terrier",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "dogue de bordeaux",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "dama gazelle",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "mimic poison frog",
    "amazon milk frog",
    "dyeing dart frog",
    "phantasmal poison frog",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "doberman",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "british timber",
    "pink fairy armadillo",
    "eurasian jay",
    "mandarin rat snake",
    "blue gourami",
    "rainbow wrasse",
    "scarlet tanager",
    "green iguana",
    "mandarin vole",
    "blue-tailed skink",
    "scarlet ibis",
    "glossy ibis",
    "mandarin catfish",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "bare-throated bellbird",
    "king bird-of-paradise",
    "wilson's bird-of-paradise",
    "cocker spaniel",
    "pit bull terrier",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jack russel terrier",
    "chihuahua",
    "whippet",
    "shih tzu",
    "puli",
    "eastern bluebird",
    "peregrine falcon",
    "pug",
    "great dane",
    "schnauzer",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "goldcrest",
    "common yellowthroat",
    "welcome swallow",
    "white-throated swift",
    "black vulture",
    "violet-green swallow",
    "house finch",
    "yellow-bellied sapsucker",
    "common moorhen",
    "great crested grebe",
    "chimney swift",
    "silvereye",
    "eurasian golden oriole",
    "pink-eared duck",
    "black-chinned hummingbird",
    "lazuli bunting",
    "anna's hummingbird",
    "green heron",
    "yellow-breasted chat",
    "chestnut-collared longspur",
    "yellow-billed cuckoo",
    "tui",
    "superb lyrebird",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "japanese serow",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki"
  ],
  "ears": [
    "mouse",
    "horse",
    "moose",
    "sheep",
    "seal",
    "monkey",
    "meerkat",
    "brown bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "otter",
    "chameleon",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "pangolin",
    "gharial",
    "marine iguana",
    "porcupine",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "african civet",
    "african penguin",
    "anteater",
    "armadillo",
    "baboon",
    "barn owl",
    "european bison",
    "bobcat",
    "budgerigar",
    "capybara",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "european hare",
    "fennec fox",
    "gemsbok",
    "jackal",
    "ring-tailed lemur",
    "llama",
    "european lynx",
    "japanese macaque",
    "mountain goat",
    "opossum",
    "pine marten",
    "polar bear",
    "red squirrel",
    "red fox",
    "roborovski hamster",
    "serval",
    "snow leopard",
    "hyena",
    "weasel",
    "wildebeest",
    "wolverine",
    "arctic hare",
    "beaver",
    "camel",
    "chamois",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "cuscus",
    "dhole",
    "donkey",
    "dormouse",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "fangtooth",
    "ferret",
    "gopher",
    "hippopotamus",
    "honey badger",
    "saola",
    "golden-rumped elephant shrew",
    "dama gazelle",
    "chinese crested",
    "amur leopard",
    "javan rhino",
    "hirola",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "rainbow lorikeet",
    "killer whale",
    "pink fairy armadillo",
    "ringtail possum",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "muntjac deer",
    "java mouse-deer",
    "aardwolf",
    "numbat",
    "japanese serow",
    "long-eared owl",
    "long-eared jerboa",
    "american curl",
    "black-tailed jackrabbit",
    "kangaroo rat",
    "red kangaroo",
    "mule deer",
    "american brahman",
    "galago",
    "german shepherd",
    "cocker spaniel",
    "collie",
    "whippet",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "harvest mouse",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "pygmy marmoset",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki"
  ],
  "eyes": [
    "mouse",
    "duck",
    "horse",
    "moose",
    "sheep",
    "crocodile",
    "bat",
    "seal",
    "monkey",
    "meerkat",
    "bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "flamingo",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "afghan hound",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bedlington terrier",
    "bison",
    "bobcat",
    "brown bear",
    "budgerigar",
    "capybara",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "affenpinscher",
    "ainu dog",
    "airedale terrier",
    "giant tortoise",
    "river dolphin",
    "american bulldog",
    "clawed frog",
    "angelfish",
    "ant",
    "appenzeller dog",
    "giant hornet",
    "cattle dog",
    "australian shepherd",
    "barracuda",
    "basenji",
    "basking shark",
    "basset hound",
    "bearded dragon",
    "beaver",
    "bichon frise",
    "birman",
    "black russian terrier",
    "bloodhound",
    "blue jay",
    "blue whale",
    "bluetick coonhound",
    "bombay",
    "booby",
    "border collie",
    "border terrier",
    "boston terrier",
    "boxer",
    "bumblebee",
    "bullfrog",
    "bull shark",
    "bull terrier",
    "great white shark",
    "cairn terrier",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "dogue de bordeaux",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "dama gazelle",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "mimic poison frog",
    "amazon milk frog",
    "dyeing dart frog",
    "phantasmal poison frog",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "doberman",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "british timber",
    "pink fairy armadillo",
    "eurasian jay",
    "mandarin rat snake",
    "blue gourami",
    "rainbow wrasse",
    "scarlet tanager",
    "green iguana",
    "mandarin vole",
    "blue-tailed skink",
    "scarlet ibis",
    "glossy ibis",
    "mandarin catfish",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "bare-throated bellbird",
    "king bird-of-paradise",
    "wilson's bird-of-paradise",
    "cocker spaniel",
    "pit bull terrier",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jack russel terrier",
    "chihuahua",
    "whippet",
    "shih tzu",
    "puli",
    "eastern bluebird",
    "peregrine falcon",
    "pug",
    "great dane",
    "schnauzer",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "goldcrest",
    "common yellowthroat",
    "welcome swallow",
    "white-throated swift",
    "black vulture",
    "violet-green swallow",
    "house finch",
    "yellow-bellied sapsucker",
    "common moorhen",
    "great crested grebe",
    "chimney swift",
    "silvereye",
    "eurasian golden oriole",
    "pink-eared duck",
    "black-chinned hummingbird",
    "lazuli bunting",
    "anna's hummingbird",
    "green heron",
    "yellow-breasted chat",
    "chestnut-collared longspur",
    "yellow-billed cuckoo",
    "tui",
    "superb lyrebird",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "japanese serow"
  ],
  "nose": [
    "seal",
    "meerkat",
    "bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fossa",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "afghan hound",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bedlington terrier",
    "bison",
    "bobcat",
    "brown bear",
    "budgerigar",
    "capybara",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "affenpinscher",
    "ainu dog",
    "airedale terrier",
    "giant tortoise",
    "river dolphin",
    "american bulldog",
    "clawed frog",
    "angelfish",
    "ant",
    "giant hornet",
    "barracuda",
    "basenji",
    "basking shark",
    "bearded dragon",
    "beaver",
    "blue jay",
    "blue whale",
    "bluetick coonhound",
    "bombay",
    "booby",
    "bumblebee",
    "bullfrog",
    "bull shark",
    "bull terrier",
    "great white shark",
    "cairn terrier",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "dogue de bordeaux",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "flamingo",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "dama gazelle",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "doberman",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "british timber",
    "pink fairy armadillo",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "cocker spaniel",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jack russel terrier",
    "chihuahua",
    "whippet",
    "shih tzu",
    "eastern bluebird",
    "peregrine falcon",
    "pug",
    "great dane",
    "schnauzer",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "japanese serow",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "harvest mouse",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki",
    "star-nosed mole",
    "snub-nosed monkey",
    "proboscis monkey",
    "tapir"
  ],
  "legs": [
    "seal",
    "meerkat",
    "bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "afghan hound",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bedlington terrier",
    "bison",
    "bobcat",
    "brown bear",
    "budgerigar",
    "capybara",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "affenpinscher",
    "ainu dog",
    "airedale terrier",
    "giant tortoise",
    "river dolphin",
    "american bulldog",
    "clawed frog",
    "angelfish",
    "ant",
    "appenzeller dog",
    "giant hornet",
    "cattle dog",
    "australian shepherd",
    "barracuda",
    "basenji",
    "basking shark",
    "basset hound",
    "bearded dragon",
    "beaver",
    "bichon frise",
    "birman",
    "black russian terrier",
    "bloodhound",
    "blue jay",
    "blue whale",
    "bluetick coonhound",
    "bombay",
    "booby",
    "border collie",
    "border terrier",
    "boston terrier",
    "boxer",
    "bumblebee",
    "bullfrog",
    "bull shark",
    "bull terrier",
    "great white shark",
    "cairn terrier",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "dogue de bordeaux",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "flamingo",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "dama gazelle",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "mimic poison frog",
    "amazon milk frog",
    "dyeing dart frog",
    "phantasmal poison frog",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "doberman",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "british timber",
    "pink fairy armadillo",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "cocker spaniel",
    "pit bull terrier",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jack russel terrier",
    "chihuahua",
    "whippet",
    "shih tzu",
    "puli",
    "eastern bluebird",
    "peregrine falcon",
    "pug",
    "great dane",
    "schnauzer",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "japanese serow",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "harvest mouse",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki"
  ],
  "feet": [
    "seal",
    "meerkat",
    "bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "afghan hound",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bedlington terrier",
    "bison",
    "bobcat",
    "brown bear",
    "budgerigar",
    "capybara",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "affenpinscher",
    "ainu dog",
    "airedale terrier",
    "giant tortoise",
    "river dolphin",
    "american bulldog",
    "clawed frog",
    "angelfish",
    "ant",
    "appenzeller dog",
    "giant hornet",
    "cattle dog",
    "australian shepherd",
    "barracuda",
    "basenji",
    "basking shark",
    "basset hound",
    "bearded dragon",
    "beaver",
    "bichon frise",
    "birman",
    "black russian terrier",
    "bloodhound",
    "blue jay",
    "blue whale",
    "bluetick coonhound",
    "bombay",
    "booby",
    "border collie",
    "border terrier",
    "boston terrier",
    "boxer",
    "bumblebee",
    "bullfrog",
    "bull shark",
    "bull terrier",
    "great white shark",
    "cairn terrier",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "dogue de bordeaux",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "flamingo",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "dama gazelle",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "mimic poison frog",
    "amazon milk frog",
    "dyeing dart frog",
    "phantasmal poison frog",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "pink fairy armadillo",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "cocker spaniel",
    "pit bull terrier",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jack russel terrier",
    "chihuahua",
    "whippet",
    "shih tzu",
    "puli",
    "eastern bluebird",
    "peregrine falcon",
    "pug",
    "great dane",
    "schnauzer",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "japanese serow"
  ],
  "tail": [
    "seal",
    "meerkat",
    "bear",
    "elephant",
    "gazelle",
    "lion",
    "tiger",
    "wolf",
    "camel",
    "otter",
    "chameleon",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "angora rabbit",
    "axolotl",
    "red panda",
    "cheetah",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "arctic fox",
    "aardvark",
    "afghan hound",
    "african civet",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "bedlington terrier",
    "bison",
    "bobcat",
    "brown bear",
    "clownfish",
    "coati",
    "cottontop tamarin",
    "coyote",
    "european hare",
    "fennec fox",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "mountain goat",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "seahorse",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "giant tortoise",
    "river dolphin",
    "barn owl",
    "barracuda",
    "basenji",
    "bearded dragon",
    "beaver",
    "bichon frise",
    "birman",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "flamingo",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetzal",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "bumblebee",
    "dama gazelle",
    "chinese crested",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "scarlet macaw",
    "peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "red-eyed tree frog",
    "rainbow trout",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "budgerigar",
    "british timber",
    "pink fairy armadillo",
    "ringtail possum",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "cocker spaniel",
    "pit bull terrier",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jack russel terrier",
    "chihuahua",
    "spider monkey",
    "scorpion",
    "long-tailed widowbird",
    "indian giant squirrel",
    "turquoise-browed motmot",
    "greater racket-tailed drongo",
    "long-eared jerboa",
    "wilson's bird-of-paradise",
    "lady amherst's pheasant",
    "superb lyrebird",
    "raccoon",
    "bushy-tailed mongoose",
    "striped skunk",
    "binturong",
    "short-tailed shrew",
    "saluki",
    "alaskan malamute",
    "japanese serow",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "harvest mouse",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "pygmy marmoset",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki"
  ],
  "coat": [
    "bear",
    "elephant",
    "lion",
    "tiger",
    "wolf",
    "chameleon",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "okapi",
    "maned wolf",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "brown-throated sloth",
    "sea turtle",
    "pangolin",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "panther",
    "millipede",
    "aardvark",
    "african civet",
    "african penguin",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "bison",
    "bobcat",
    "brown bear",
    "budgerigar",
    "capybara",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "emu",
    "european hare",
    "fennec fox",
    "hammerhead shark",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "hyena",
    "toucan",
    "weasel",
    "wildebeest",
    "giant tortoise",
    "river dolphin",
    "angelfish",
    "ant",
    "giant hornet",
    "barn owl",
    "barracuda",
    "basking shark",
    "bearded dragon",
    "beaver",
    "cassowary",
    "t-rex",
    "catfish",
    "camel",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "clownfish",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "flamingo",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "narwhal",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "bumblebee",
    "dama gazelle",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "scarlet macaw",
    "mandarin duck",
    "piebald peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "red panda",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "green anole",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "pink fairy armadillo",
    "ringtail possum",
    "centipede",
    "philippine eagle",
    "gharial",
    "cleaner shrimp",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "wolverine",
    "stoat",
    "honey badger",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "stegosaurus",
    "parasaurolophus",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "rosy maple moth",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "highland cow",
    "silkie chicken",
    "musk ox",
    "norwegian forest cat",
    "polish buff laced chicken",
    "valais blacknose sheep",
    "racka sheep",
    "bedlington terrier",
    "chinese crested",
    "afghan hound",
    "poodle",
    "shetland sheepdog",
    "schnauzer",
    "saluki",
    "old english sheepdog",
    "irish wolfhound",
    "yorkshire terrier",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "harvest mouse",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki",
    "tahr"
  ],
  "colour": [
    "meerkat",
    "dorcas gazelle",
    "dama gazelle",
    "lion",
    "tiger",
    "grey wolf",
    "camel",
    "sea otter",
    "large white pig",
    "wild boar",
    "nubian goat",
    "nigerian goat",
    "irish cob",
    "arabian horse",
    "okapi",
    "maned wolf",
    "fosse",
    "slow lori",
    "angora rabbit",
    "axolotl",
    "bearded vulture",
    "red panda",
    "cheetah",
    "glass frog",
    "mantis shrimp",
    "sun bear",
    "aye-aye",
    "markhor",
    "saiga antelope",
    "sloth",
    "sea turtle",
    "pangolin",
    "gharial",
    "marine iguana",
    "white tiger",
    "porcupine",
    "african crowned crane",
    "african wild dog",
    "leopard",
    "bat-eared fox",
    "bongo",
    "orangutan",
    "sea lion",
    "caracal",
    "giraffe",
    "rhino",
    "howler monkey",
    "mountain lion",
    "koala",
    "arctic fox",
    "african civet",
    "african penguin",
    "akita",
    "anteater",
    "arctic hare",
    "armadillo",
    "baboon",
    "barn owl",
    "bison",
    "bobcat",
    "brown bear",
    "budgerigar",
    "cassowary",
    "clownfish",
    "coati",
    "common frog",
    "cottontop tamarin",
    "coyote",
    "dachshund",
    "emu",
    "european hare",
    "fennec fox",
    "gemsbok",
    "golden pheasant",
    "common pheasant",
    "rainbow grasshopper",
    "pelican",
    "honey bee",
    "hoopoe bird",
    "jackal",
    "king penguin",
    "komodo dragon",
    "ladybug",
    "ring-tailed lemur",
    "llama",
    "lynx",
    "japanese macaque",
    "mountain goat",
    "tarantula",
    "opossum",
    "pine marten",
    "pirahna",
    "polar bear",
    "red squirrel",
    "red fox",
    "kangaroo",
    "roborovski hamster",
    "ibis",
    "scarlet macaw",
    "seahorse",
    "secretary bird",
    "serval",
    "snow leopard",
    "brown hyena",
    "keel billed toucan",
    "weasel",
    "wildebeest",
    "wolverine",
    "abyssinian",
    "giant tortoise",
    "river dolphin",
    "clawed frog",
    "royal angelfish",
    "ant",
    "giant hornet",
    "barracuda",
    "basking shark",
    "bearded dragon",
    "beaver",
    "blue jay",
    "blue whale",
    "bombay",
    "booby",
    "buff-tailed bumblebee",
    "bullfrog",
    "bull shark",
    "great white shark",
    "t-rex",
    "stegosaurus",
    "catfish",
    "chamois",
    "caterpillar",
    "chicken",
    "chinchilla",
    "chipmunk",
    "collared peccary",
    "colossal squid",
    "cichlid",
    "cuscus",
    "darwin's frog",
    "dhole",
    "discus",
    "dodo",
    "donkey",
    "dragonfly",
    "dormouse",
    "earwig",
    "echidna",
    "emperor tamarin",
    "fishing cat",
    "flamingo",
    "fangtooth",
    "ferret",
    "gecko",
    "gila monster",
    "german shepherd",
    "gopher",
    "grouse",
    "harpy eagle",
    "hippopotamus",
    "heron",
    "honey badger",
    "narwhal",
    "green anole",
    "golden retriever",
    "lamprey",
    "kiwi",
    "mudskipper",
    "potoo",
    "mandarin fish",
    "lovebird",
    "wigeon",
    "saola",
    "cuban snail",
    "bald ibis",
    "ploughshare tortoise",
    "resplendent quetza",
    "angel shark",
    "golden-rumped elephant shrew",
    "peacock tarantula",
    "blue poison dart frog",
    "red-eyed tree frog",
    "golden poison frog",
    "chinese crested",
    "mimic poison frog",
    "amazon milk frog",
    "dyeing dart frog",
    "phantasmal poison frog",
    "lilac-breasted roller",
    "swallowtail butterfly",
    "california red-sided garter snake",
    "gouldian finch",
    "rosy maple moth",
    "mandarin duck",
    "san francisco garter snake",
    "rainbow boa",
    "emerald tree boa",
    "jewel bug",
    "betta fish",
    "amur leopard",
    "vaquita",
    "javan rhino",
    "baiji dolphin",
    "hirola",
    "fiery-throated hummingbird",
    "carnotaurus",
    "madagascar pochard",
    "nile lechwe",
    "iberian lynx",
    "zebu",
    "yak",
    "peacock",
    "rainbow lorikeet",
    "harlequin tuskfish",
    "electric blue gecko",
    "killer whale",
    "blue morpho butterfly",
    "rainbow trout",
    "doberman",
    "leaf insect",
    "yellow tang",
    "rainbow bee-eater",
    "blue-ringed octopus",
    "british timber",
    "pink fairy armadillo",
    "ringtail possum",
    "rice weevil",
    "centipede",
    "cockroach",
    "mosquito",
    "philippine eagle",
    "cleaner shrimp",
    "rain frog",
    "european pine marten",
    "european badger",
    "eurasian otter",
    "stoat",
    "leaf sheep",
    "ocean angel",
    "palmato gecko",
    "muntjac deer",
    "java mouse-deer",
    "blue ridge two-lined salamander",
    "aardwolf",
    "numbat",
    "eastern bluebird",
    "peregrine falcon",
    "jellyfish",
    "horseshoe crab",
    "hedgehog",
    "tyrannosaurus",
    "triceratops",
    "parasaurolophus",
    "harpy",
    "chimera",
    "allosaurus",
    "brachiosaurus",
    "ankylosaurus",
    "utahraptor",
    "pterodactylus",
    "spinosaurus",
    "griffin",
    "leafy sea dragon",
    "musk deer",
    "blue glaucus",
    "goldfinch",
    "spiny softshell turtle",
    "american white pelican",
    "golden tortoise beetle",
    "indian painted grasshopper",
    "cairns birdwing",
    "thorn treehopper",
    "spiny flower mantis",
    "european peacock butterfly",
    "lantern bug",
    "malay lacewing",
    "rainbow stag beetle",
    "tailed jay",
    "pygmy rabbit",
    "pygmy marmoset",
    "etruscan shrew",
    "mandrill",
    "wattle-cup caterpillar",
    "greater earless lizard",
    "peacock spider",
    "lesser redpoll",
    "bullfinch",
    "golden oriole",
    "siskin",
    "green woodpecker",
    "capercaillie",
    "ring-necked parakeet",
    "eurasian jay",
    "blue tit",
    "kingfisher",
    "european bee-eater",
    "boeseman's rainbowfish",
    "cameroon dwarf gecko",
    "forest caterpillar hunter",
    "iridescent tiger beetle",
    "madagascan sunset moth",
    "orange-breasted sunbird",
    "painted bunting",
    "panther chameleon",
    "parrotfish",
    "red-capped parrot",
    "sally lightfoot crab",
    "scarlet-chested parrot",
    "sun conure",
    "cortez rainbow wrasse",
    "ornare wrasse",
    "zigzag wrasse",
    "yellow-banded poison dart frog",
    "resplendent quetzal",
    "oriental dwarf kingfisher",
    "nicobar pigeon",
    "halloween crab",
    "pink-necked green pigeon",
    "spider-man agama",
    "violet-backed starling",
    "black-browed barbet",
    "turquoise-browed motmot",
    "rosemary beetle",
    "paradise tanager",
    "flower hat jelly",
    "picasso bug",
    "eastern collared lizard",
    "scarlet tanager",
    "blood-red glider",
    "scarlet peacock butterfly",
    "red milk snake",
    "yellow cobra guppy",
    "fire skink",
    "common green forest lizard",
    "monarch butterfly",
    "clown nudibranch",
    "koi fish",
    "european firebug",
    "ailanthus webworm moth",
    "venezuelan troupial",
    "sira poison dart frog",
    "yellowtail coris",
    "western spindalis",
    "yellow boxfish",
    "climbing mantella",
    "yellow longnose butterflyfish",
    "banana nudibranch",
    "gold lace nudibranch",
    "great tit",
    "lemonpeel angelfish",
    "golden conure",
    "bluestripe snapper",
    "yellow-breasted chat",
    "green keel-bellied lizard",
    "green-headed tanager",
    "golden-tailed sapphire",
    "golden-fronted leafbird",
    "emerald tree monitor",
    "glorious scarab",
    "common dolphinfish",
    "green terror cichlid",
    "leaf slug",
    "european green toad",
    "dogbane beetle",
    "inca jay",
    "blue tree monitor",
    "blue dacnis",
    "florida scrub-jay",
    "portuguese man o' war",
    "rainbow whiptail",
    "hyacinth macaw",
    "blue tang",
    "shining honeycreeper",
    "periander metalmark",
    "yellowstriped fairy basslet",
    "purple emperor",
    "purple grenadier",
    "purple gallinule",
    "royal gramma",
    "spanish shawl",
    "two spined anglefish",
    "purple firefish",
    "purple-crested turaco",
    "pink-headed warbler",
    "roseate spoonbill",
    "major mitchell's cockatoo",
    "bourke's parakeet",
    "common buckeye butterfly",
    "little bunting",
    "pied tamarin",
    "brown trout",
    "brown-winged kingfisher",
    "brown booby",
    "european fire-bellied toad",
    "brandt's cormorant",
    "african grey parrot",
    "lagoon triggerfish",
    "grey four-eyed opossum",
    "grey plover",
    "snow owl",
    "salt marsh moth",
    "dalmatian",
    "bernese mountain dog",
    "beagle",
    "siberian husky",
    "catahoula",
    "zebra",
    "striped chipmunk",
    "spotted genet",
    "fallow deer",
    "axis deer",
    "azara's agouti",
    "black lemur",
    "prairie dog",
    "dwarf mongoose",
    "reindeer",
    "european mink",
    "harvest mouse",
    "kulan",
    "patagonian mara",
    "przewalski's wild horse",
    "wallaby",
    "takin",
    "vicuna",
    "white-face saki"
  ]
};

export const EXTRAS = [
  "unicorn horn",
  "nose horn",
  "reindeer antlers",
  "long eyelashes",
  "huge ears",
  "cactus spikes",
  "huge eyes",
  "piebaldism",
  "insect antennae",
  "moose antlers",
  "bee stinger",
  "glowing eyes",
  "iridescence",
  "long whiskers",
  "fangs",
  "extra eyes",
  "sheep horns",
  "albinism",
  "melanism",
  "spines along the back",
  "bioluminescent",
  "erythrism",
  "heterochromia",
  "leucism",
  "xanthochromish",
  "hairless",
  "embedded gems",
  "plants",
  "mushrooms",
  "alien antennae",
  "sparkles",
  "ear tufts",
  "dragon wings",
  "bird wings",
  "multiple tails",
  "long claws",
  "mane",
  "fluffy cheeks",
  "fluffy ears",
  "colourful spots",
  "colourful stripes",
  "tusks",
  "roe deer antlers",
  "slime",
  "ankole watusi horns",
  "gills",
  "anglerfish lure",
  "crest feathers",
  "none"
];

export const TYPES = {"harvest mouse":"mammal","duck":"bird","horse":"mammal","moose":"mammal","sheep":"mammal","crocodile":"reptile","bat":"mammal","seal":"mammal","monkey":"mammal","meerkat":"mammal","brown bear":"mammal","sloth bear":"mammal","elephant":"mammal","gazelle":"mammal","lion":"mammal","tiger":"mammal","wolf":"mammal","camel":"mammal","otter":"mammal","chameleon":"reptile","flamingo":"bird","large white pig":"mammal","wild boar":"mammal","nubian goat":"mammal","nigerian goat":"mammal","irish cob":"mammal","arabian horse":"mammal","okapi":"mammal","maned wolf":"mammal","fosse":"mammal","slow lori":"mammal","angora rabbit":"mammal","axolotl":"amphibian","bearded vulture":"bird","red panda":"mammal","cheetah":"mammal","glass frog":"amphibian","mantis shrimp":"sea","sun bear":"mammal","aye-aye":"mammal","markhor":"mammal","saiga antelope":"mammal","sloth":"mammal","sea turtle":"reptile","pangolin":"mammal","gharial":"reptile","marine iguana":"reptile","white tiger":"mammal","porcupine":"mammal","african crowned crane":"bird","african wild dog":"mammal","leopard":"mammal","bat-eared fox":"mammal","bongo":"mammal","orangutan":"mammal","sea lion":"mammal","caracal":"mammal","giraffe":"mammal","rhino":"mammal","howler monkey":"mammal","mountain lion":"mammal","koala":"mammal","arctic fox":"mammal","panther":"mammal","millipede":"bug","aardvark":"mammal","afghan hound":"mammal","african civet":"mammal","african penguin":"bird","akita":"mammal","anteater":"mammal","arctic hare":"mammal","armadillo":"mammal","baboon":"mammal","barn owl":"bird","bedlington terrier":"mammal","bison":"mammal","bobcat":"mammal","budgerigar":"bird","capybara":"mammal","cassowary":"bird","clownfish":"fish","coati":"mammal","common frog":"amphibian","cottontop tamarin":"mammal","coyote":"mammal","dachshund":"mammal","emu":"bird","european hare":"mammal","fennec fox":"mammal","hammerhead shark":"fish","gemsbok":"mammal","golden pheasant":"bird","common pheasant":"bird","grasshopper":"insect","pelican":"bird","honey bee":"insect","hoopoe bird":"bird","jackal":"mammal","king penguin":"bird","komodo dragon":"reptile","ladybug":"insect","ring-tailed lemur":"mammal","llama":"mammal","lynx":"mammal","japanese macaque":"mammal","mountain goat":"mammal","tarantula":"bug","opossum":"mammal","pine marten":"mammal","pirahna":"fish","polar bear":"mammal","red squirrel":"mammal","red fox":"mammal","kangaroo":"mammal","roborovski hamster":"mammal","ibis":"bird","scarlet macaw":"bird","seahorse":"fish","secretary bird":"bird","serval":"mammal","snow leopard":"mammal","hyena":"mammal","toucan":"bird","weasel":"mammal","wildebeest":"mammal","wolverine":"mammal","abyssinian":"mammal","giant tortoise":"reptile","river dolphin":"mammal","clawed frog":"amphibian","angelfish":"fish","ant":"insect","giant hornet":"insect","barracuda":"fish","basenji":"mammal","basking shark":"fish","basset hound":"mammal","bearded dragon":"reptile","beaver":"mammal","bichon frise":"mammal","birman":"mammal","black russian terrier":"mammal","bloodhound":"mammal","blue jay":"bird","blue whale":"mammal","bombay":"mammal","booby":"bird","border collie":"mammal","boxer":"mammal","bumblebee":"insect","bullfrog":"amphibian","bull shark":"fish","bull terrier":"mammal","great white shark":"fish","t-rex":"dino","stegosaurus":"dino","catfish":"fish","chamois":"mammal","caterpillar":"insect","chicken":"bird","chinchilla":"mammal","chipmunk":"mammal","collared peccary":"mammal","colossal squid":"sea","cichlid":"fish","cuscus":"mammal","darwin's frog":"amphibian","dhole":"mammal","discus":"fish","dodo":"bird","dogue de bordeaux":"mammal","donkey":"mammal","dragonfly":"insect","dormouse":"mammal","earwig":"insect","echidna":"mammal","emperor tamarin":"mammal","fishing cat":"mammal","fangtooth":"fish","ferret":"mammal","gecko":"reptile","gila monster":"reptile","german shepherd":"mammal","gopher":"mammal","grouse":"bird","harpy eagle":"bird","hippopotamus":"mammal","heron":"bird","honey badger":"mammal","narwhal":"mammal","green anole":"reptile","golden retriever":"mammal","lamprey":"fish","kiwi":"bird","mudskipper":"fish","potoo":"bird","mandarin fish":"fish","lovebird":"bird","wigeon":"bird","saola":"mammal","cuban snail":"sea","bald ibis":"bird","ploughshare tortoise":"reptile","resplendent quetza":"bird","angel shark":"fish","golden-rumped elephant shrew":"mammal","peacock tarantula":"bug","dama gazelle":"mammal","blue poison dart frog":"amphibian","red-eyed tree frog":"amphibian","golden poison frog":"amphibian","chinese crested":"mammal","mimic poison frog":"amphibian","amazon milk frog":"amphibian","dyeing dart frog":"amphibian","phantasmal poison frog":"amphibian","lilac-breasted roller":"bird","swallowtail butterfly":"insect","california red-sided garter snake":"reptile","gouldian finch":"bird","rosy maple moth":"insect","mandarin duck":"bird","san francisco garter snake":"reptile","rainbow boa":"reptile","emerald tree boa":"reptile","jewel bug":"insect","betta fish":"fish","amur leopard":"mammal","vaquita":"mammal","javan rhino":"mammal","baiji dolphin":"mammal","hirola":"mammal","fiery-throated hummingbird":"bird","carnotaurus":"dino","madagascar pochard":"bird","nile lechwe":"mammal","iberian lynx":"mammal","zebu":"mammal","yak":"mammal","piebald peacock":"bird","rainbow lorikeet":"bird","harlequin tuskfish":"fish","electric blue gecko":"reptile","killer whale":"mammal","blue morpho butterfly":"insect","rainbow trout":"fish","doberman":"mammal","leaf insect":"insect","yellow tang":"fish","rainbow bee-eater":"bird","blue-ringed octopus":"sea","british timber":"mammal","pink fairy armadillo":"mammal","eurasian jay":"bird","mandarin rat snake":"reptile","blue gourami":"fish","rainbow wrasse":"fish","scarlet tanager":"bird","green iguana":"reptile","mandarin vole":"mammal","blue-tailed skink":"reptile","scarlet ibis":"bird","glossy ibis":"bird","mandarin catfish":"fish","ringtail possum":"mammal","rice weevil":"insect","centipede":"bug","cockroach":"insect","mosquito":"insect","philippine eagle":"bird","cleaner shrimp":"sea","rain frog":"amphibian","european pine marten":"mammal","european badger":"mammal","eurasian otter":"mammal","stoat":"mammal","leaf sheep":"sea","ocean angel":"sea","palmato gecko":"reptile","muntjac deer":"mammal","bare-throated bellbird":"bird","king bird-of-paradise":"bird","wilson's bird-of-paradise":"bird","java mouse-deer":"mammal","blue ridge two-lined salamander":"amphibian","aardwolf":"mammal","numbat":"mammal","chihuahua":"mammal","whippet":"mammal","shih tzu":"mammal","puli":"mammal","eastern bluebird":"bird","peregrine falcon":"bird","jellyfish":"sea","horseshoe crab":"sea","hedgehog":"mammal","tyrannosaurus":"dino","triceratops":"dino","parasaurolophus":"dino","harpy":"mythical","chimera":"mythical","allosaurus":"dino","brachiosaurus":"dino","ankylosaurus":"dino","utahraptor":"dino","pterodactylus":"dino","spinosaurus":"dino","griffin":"mythical","leafy sea dragon":"fish","musk deer":"mammal","blue glaucus":"sea","goldfinch":"bird","spiny softshell turtle":"reptile","goldcrest":"bird","common yellowthroat":"bird","welcome swallow":"bird","white-throated swift":"bird","black vulture":"bird","violet-green swallow":"bird","house finch":"bird","yellow-bellied sapsucker":"bird","common moorhen":"bird","great crested grebe":"bird","chimney swift":"bird","silvereye":"bird","eurasian golden oriole":"bird","pink-eared duck":"bird","black-chinned hummingbird":"bird","lazuli bunting":"bird","anna's hummingbird":"bird","green heron":"bird","yellow-breasted chat":"bird","chestnut-collared longspur":"bird","yellow-billed cuckoo":"bird","tui":"bird","superb lyrebird":"bird","american white pelican":"bird","golden tortoise beetle":"insect","indian painted grasshopper":"insect","cairns birdwing":"insect","thorn treehopper":"insect","spiny flower mantis":"insect","european peacock butterfly":"insect","lantern bug":"insect","malay lacewing":"insect","rainbow stag beetle":"insect","tailed jay":"insect","pygmy rabbit":"mammal","pygmy marmoset":"mammal","etruscan shrew":"mammal","japanese serow":"mammal","azara's agouti":"mammal","black lemur":"mammal","prairie dog":"mammal","dwarf mongoose":"mammal","reindeer":"mammal","european mink":"mammal","kulan":"mammal","patagonian mara":"mammal","przewalski's wild horse":"mammal","wallaby":"mammal","takin":"mammal","vicuna":"mammal","white-face saki":"mammal","affenpinscher":"mammal","ainu dog":"mammal","airedale terrier":"mammal","american bulldog":"mammal","appenzeller dog":"mammal","cattle dog":"mammal","australian shepherd":"mammal","bluetick coonhound":"mammal","border terrier":"mammal","boston terrier":"mammal","cairn terrier":"mammal","cocker spaniel":"mammal","pit bull terrier":"mammal","jack russel terrier":"mammal","pug":"mammal","great dane":"mammal","schnauzer":"mammal","mouse":"mammal","european bison":"mammal","european lynx":"mammal","long-eared owl":"bird","long-eared jerboa":"mammal","american curl":"mammal","black-tailed jackrabbit":"mammal","kangaroo rat":"mammal","red kangaroo":"mammal","mule deer":"mammal","american brahman":"mammal","galago":"mammal","collie":"mammal","bear":"mammal","fossa":"mammal","star-nosed mole":"mammal","snub-nosed monkey":"mammal","proboscis monkey":"mammal","tapir":"mammal","resplendent quetzal":"bird","peacock":"bird","spider monkey":"mammal","scorpion":"bug","long-tailed widowbird":"bird","indian giant squirrel":"mammal","turquoise-browed motmot":"bird","greater racket-tailed drongo":"bird","lady amherst's pheasant":"bird","raccoon":"mammal","bushy-tailed mongoose":"mammal","striped skunk":"mammal","binturong":"mammal","short-tailed shrew":"mammal","saluki":"mammal","alaskan malamute":"mammal","brown-throated sloth":"mammal","highland cow":"mammal","silkie chicken":"bird","musk ox":"mammal","norwegian forest cat":"mammal","polish buff laced chicken":"bird","valais blacknose sheep":"mammal","racka sheep":"mammal","poodle":"mammal","shetland sheepdog":"mammal","old english sheepdog":"mammal","irish wolfhound":"mammal","yorkshire terrier":"mammal","tahr":"mammal","dorcas gazelle":"mammal","grey wolf":"mammal","sea otter":"mammal","rainbow grasshopper":"insect","brown hyena":"mammal","keel billed toucan":"bird","royal angelfish":"fish","buff-tailed bumblebee":"insect","mandrill":"mammal","wattle-cup caterpillar":"insect","greater earless lizard":"reptile","peacock spider":"bug","lesser redpoll":"bird","bullfinch":"bird","golden oriole":"bird","siskin":"bird","green woodpecker":"bird","capercaillie":"bird","ring-necked parakeet":"bird","blue tit":"bird","kingfisher":"bird","european bee-eater":"bird","boeseman's rainbowfish":"fish","cameroon dwarf gecko":"reptile","forest caterpillar hunter":"insect","iridescent tiger beetle":"insect","madagascan sunset moth":"insect","orange-breasted sunbird":"bird","painted bunting":"bird","panther chameleon":"reptile","parrotfish":"fish","red-capped parrot":"bird","sally lightfoot crab":"sea","scarlet-chested parrot":"bird","sun conure":"bird","cortez rainbow wrasse":"fish","ornare wrasse":"fish","zigzag wrasse":"fish","yellow-banded poison dart frog":"amphibian","oriental dwarf kingfisher":"bird","nicobar pigeon":"bird","halloween crab":"sea","pink-necked green pigeon":"bird","spider-man agama":"reptile","violet-backed starling":"bird","black-browed barbet":"bird","rosemary beetle":"insect","paradise tanager":"bird","flower hat jelly":"sea","picasso bug":"insect","eastern collared lizard":"reptile","blood-red glider":"insect","scarlet peacock butterfly":"insect","red milk snake":"reptile","yellow cobra guppy":"fish","fire skink":"reptile","common green forest lizard":"reptile","monarch butterfly":"insect","clown nudibranch":"sea","koi fish":"fish","european firebug":"insect","ailanthus webworm moth":"insect","venezuelan troupial":"bird","sira poison dart frog":"amphibian","yellowtail coris":"fish","western spindalis":"bird","yellow boxfish":"fish","climbing mantella":"amphibian","yellow longnose butterflyfish":"fish","banana nudibranch":"sea","gold lace nudibranch":"sea","great tit":"bird","lemonpeel angelfish":"fish","golden conure":"bird","bluestripe snapper":"fish","green keel-bellied lizard":"reptile","green-headed tanager":"bird","golden-tailed sapphire":"bird","golden-fronted leafbird":"bird","emerald tree monitor":"reptile","glorious scarab":"insect","common dolphinfish":"fish","green terror cichlid":"fish","leaf slug":"sea","european green toad":"amphibian","dogbane beetle":"insect","inca jay":"bird","blue tree monitor":"reptile","blue dacnis":"bird","florida scrub-jay":"bird","portuguese man o' war":"sea","rainbow whiptail":"reptile","hyacinth macaw":"bird","blue tang":"fish","shining honeycreeper":"bird","periander metalmark":"insect","yellowstriped fairy basslet":"fish","purple emperor":"insect","purple grenadier":"bird","purple gallinule":"bird","royal gramma":"fish","spanish shawl":"sea","two spined anglefish":"fish","purple firefish":"fish","purple-crested turaco":"bird","pink-headed warbler":"bird","roseate spoonbill":"bird","major mitchell's cockatoo":"bird","bourke's parakeet":"bird","common buckeye butterfly":"insect","little bunting":"bird","pied tamarin":"mammal","brown trout":"fish","brown-winged kingfisher":"bird","brown booby":"bird","european fire-bellied toad":"amphibian","brandt's cormorant":"bird","african grey parrot":"bird","lagoon triggerfish":"fish","grey four-eyed opossum":"mammal","grey plover":"bird","snow owl":"bird","salt marsh moth":"insect","dalmatian":"mammal","bernese mountain dog":"mammal","beagle":"mammal","siberian husky":"mammal","catahoula":"mammal","zebra":"mammal","striped chipmunk":"mammal","spotted genet":"mammal","fallow deer":"mammal","axis deer":"mammal"};
